// external declaration of sound table:

extern far cdata SNDTBL_SOUNDS;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_buenas_tardes;
extern far cdata SX_buenos_dias;
extern far cdata SX_chiste_1;
extern far cdata SX_chiste_2;
extern far cdata SX_chiste_3;
extern far cdata SX_chiste_4;
extern far cdata SX_dia_1_lunes;
extern far cdata SX_dia_2_martes;
extern far cdata SX_dia_3_miercoles;
extern far cdata SX_dia_4_jueves;
extern far cdata SX_dia_5_viernes;
extern far cdata SX_dia_6_sabado;
extern far cdata SX_dia_7_domingo;
extern far cdata SX_dia_bien;
extern far cdata SX_dormido_bien;
extern far cdata SX_escuchar_musica;
extern far cdata SX_hora_1;
extern far cdata SX_hora_2;
extern far cdata SX_hora_3;
extern far cdata SX_hora_4;
extern far cdata SX_hora_5;
extern far cdata SX_hora_6;
extern far cdata SX_hora_7;
extern far cdata SX_hora_8;
extern far cdata SX_hora_9;
extern far cdata SX_hora_10;
extern far cdata SX_hora_11;
extern far cdata SX_hora_12;
extern far cdata SX_ma_ana;
extern far cdata SX_mes_1_enero;
extern far cdata SX_mes_2_febrero;
extern far cdata SX_mes_3_marzo;
extern far cdata SX_mes_4_abril;
extern far cdata SX_mes_5_mayo;
extern far cdata SX_mes_6_junio;
extern far cdata SX_mes_7julio;
extern far cdata SX_mes_8_agosto;
extern far cdata SX_mes_9_septiembre;
extern far cdata SX_mes_11_noviembre;
extern far cdata SX_mes_11_octubre;
extern far cdata SX_mes_12_diciembre;
extern far cdata SX_min_0;
extern far cdata SX_min_5;
extern far cdata SX_min_10;
extern far cdata SX_min_15;
extern far cdata SX_min_20;
extern far cdata SX_min_25;
extern far cdata SX_min_30;
extern far cdata SX_min_35;
extern far cdata SX_min_40;
extern far cdata SX_min_45;
extern far cdata SX_min_50;
extern far cdata SX_min_55;
extern far cdata SX_no;
extern far cdata SX_num_0;
extern far cdata SX_num_1;
extern far cdata SX_num_2;
extern far cdata SX_num_3;
extern far cdata SX_num_4;
extern far cdata SX_num_5;
extern far cdata SX_num_6;
extern far cdata SX_num_7;
extern far cdata SX_num_8;
extern far cdata SX_num_9;
extern far cdata SX_num_10;
extern far cdata SX_num_11;
extern far cdata SX_num_12;
extern far cdata SX_num_13;
extern far cdata SX_num_14;
extern far cdata SX_num_15;
extern far cdata SX_num_16;
extern far cdata SX_num_17;
extern far cdata SX_num_18;
extern far cdata SX_num_19;
extern far cdata SX_num_20;
extern far cdata SX_num_21;
extern far cdata SX_num_22;
extern far cdata SX_num_23;
extern far cdata SX_num_24;
extern far cdata SX_num_25;
extern far cdata SX_num_26;
extern far cdata SX_num_27;
extern far cdata SX_num_28;
extern far cdata SX_num_29;
extern far cdata SX_num_30;
extern far cdata SX_num_31;
extern far cdata SX_num_32;
extern far cdata SX_num_33;
extern far cdata SX_num_34;
extern far cdata SX_num_35;
extern far cdata SX_num_36;
extern far cdata SX_num_37;
extern far cdata SX_num_38;
extern far cdata SX_num_39;
extern far cdata SX_pase_buen_dia;
extern far cdata SX_presentate;
extern far cdata SX_tarde;
extern far cdata SX_tienes_clase;
extern far cdata SX_uni_bien;
extern far cdata SX_chiste_oir;
extern far cdata SX_movimiento_off;
extern far cdata SX_movimiento_on;
extern far cdata SX_si;
extern far cdata SX_alarma_off;
extern far cdata SX_alarma_on;

// constants defining sounds as entries in the sound table:

#define SND_buenas_tardes       1
#define SND_buenos_dias         2
#define SND_chiste_1            3
#define SND_chiste_2            4
#define SND_chiste_3            5
#define SND_chiste_4            6
#define SND_dia_1_lunes         7
#define SND_dia_2_martes        8
#define SND_dia_3_miercoles     9
#define SND_dia_4_jueves        10
#define SND_dia_5_viernes       11
#define SND_dia_6_sabado        12
#define SND_dia_7_domingo       13
#define SND_dia_bien            14
#define SND_dormido_bien        15
#define SND_escuchar_musica     16
#define SND_hora_1              17
#define SND_hora_2              18
#define SND_hora_3              19
#define SND_hora_4              20
#define SND_hora_5              21
#define SND_hora_6              22
#define SND_hora_7              23
#define SND_hora_8              24
#define SND_hora_9              25
#define SND_hora_10             26
#define SND_hora_11             27
#define SND_hora_12             28
#define SND_ma_ana              29
#define SND_mes_1_enero         30
#define SND_mes_2_febrero       31
#define SND_mes_3_marzo         32
#define SND_mes_4_abril         33
#define SND_mes_5_mayo          34
#define SND_mes_6_junio         35
#define SND_mes_7julio          36
#define SND_mes_8_agosto        37
#define SND_mes_9_septiembre    38
#define SND_mes_11_noviembre    39
#define SND_mes_11_octubre      40
#define SND_mes_12_diciembre    41
#define SND_min_0               42
#define SND_min_5               43
#define SND_min_10              44
#define SND_min_15              45
#define SND_min_20              46
#define SND_min_25              47
#define SND_min_30              48
#define SND_min_35              49
#define SND_min_40              50
#define SND_min_45              51
#define SND_min_50              52
#define SND_min_55              53
#define SND_no                  54
#define SND_num_0               55
#define SND_num_1               56
#define SND_num_2               57
#define SND_num_3               58
#define SND_num_4               59
#define SND_num_5               60
#define SND_num_6               61
#define SND_num_7               62
#define SND_num_8               63
#define SND_num_9               64
#define SND_num_10              65
#define SND_num_11              66
#define SND_num_12              67
#define SND_num_13              68
#define SND_num_14              69
#define SND_num_15              70
#define SND_num_16              71
#define SND_num_17              72
#define SND_num_18              73
#define SND_num_19              74
#define SND_num_20              75
#define SND_num_21              76
#define SND_num_22              77
#define SND_num_23              78
#define SND_num_24              79
#define SND_num_25              80
#define SND_num_26              81
#define SND_num_27              82
#define SND_num_28              83
#define SND_num_29              84
#define SND_num_30              85
#define SND_num_31              86
#define SND_num_32              87
#define SND_num_33              88
#define SND_num_34              89
#define SND_num_35              90
#define SND_num_36              91
#define SND_num_37              92
#define SND_num_38              93
#define SND_num_39              94
#define SND_pase_buen_dia       95
#define SND_presentate          96
#define SND_tarde               97
#define SND_tienes_clase        98
#define SND_uni_bien            99
#define SND_chiste_oir          100
#define SND_movimiento_off      101
#define SND_movimiento_on       102
#define SND_si                  103
#define SND_alarma_off          104
#define SND_alarma_on           105

